version: 0.1
phases:
  install:
    commands:

  build:
    commands:

  post_build:
    commands:
      # Clear S3 bucket.
      - aws s3 rm s3://www.cicddemo.com --recursive
      # Copy files from dist to S3
      - aws s3 cp staticHosting s3://www.cicddemo.com --recursive

artifacts:
  files:
    - "**/*"
  base-directory: "serverHosting"
  discard-paths: no
      

